language: php

php:
  - 5.5
  - 5.6
  - 7.0

install: composer install

before_script:
  - composer validate --strict
  - mysql -e 'CREATE DATABASE wp_cli_test;' -uroot
  - mysql -e 'GRANT ALL PRIVILEGES ON wp_cli_test.* TO "wp_cli_test"@"localhost" IDENTIFIED BY "password1"' -uroot

script: composer run-behat

cache:
  directories:
    - vendor

notifications:
  email:
    on_success: never
    on_failure: change

before_deploy:
  - openssl aes-256-cbc -K $encrypted_70f7c684b483_key -iv $encrypted_70f7c684b483_iv -in deploy/key.enc -out deploy/key -d

deploy:
  provider: script
  script: bash deploy/deploy-plugin.sh
  skip_cleanup: true
  on:
    all_branches: true
    php: 7.0
